struct target_core_fabric_ops {
        void (*release_cmd_to_pool)(struct se_cmd_s *);
        void (*release_cmd_direct)(struct se_cmd_s *);
	int (*dev_del_lun)(struct iscsi_portal_group_s *, __u32);
	int (*stop_session)(struct iscsi_session_s *, int, int);
	void (*fall_back_to_erl0)(struct iscsi_conn_s *);
	int (*write_pending)(struct se_cmd_s *);
	void (*dec_nacl_count)(struct iscsi_node_acl_s *, struct se_cmd_s *);
	void *(*scsi_auth_intr_seq_start)(struct seq_file *, loff_t *);
	void *(*scsi_auth_intr_seq_next)(struct seq_file *, void *, loff_t *);
	int (*scsi_auth_intr_seq_show)(struct seq_file *, void *);
	void (*scsi_auth_intr_seq_stop)(struct seq_file *, void *);
	void *(*scsi_att_intr_port_seq_start)(struct seq_file *, loff_t *);
	void *(*scsi_att_intr_port_seq_next)(struct seq_file *, void *, loff_t *);
	int (*scsi_att_intr_port_seq_show)(struct seq_file *, void *);
	void (*scsi_att_intr_port_seq_stop)(struct seq_file *, void *);
	u32 (*get_task_tag)(struct se_cmd_s *);
	int (*get_cmd_state)(struct se_cmd_s *);
	void (*new_cmd_failure)(struct se_cmd_s *);
	int (*queue_data_in)(struct se_cmd_s *);
	int (*queue_status)(struct se_cmd_s *);
	int (*queue_tm_rsp)(struct se_cmd_s *);
	int (*is_state_remove)(struct se_cmd_s *);
	u64 (*pack_lun)(unsigned int);
};
